describe('My First Test', () => {
  it('Visits the Kitchen Sink', () => {
    cy.visit('https://bill-track.firebaseapp.com/#/')
    cy.contains('h1', 'Bill Tracker')
    cy.get("select")
      .select("Abby")
    cy.get("a").eq(1)
      .click()
    cy.url()
      .should("contain", "/2")
    cy.get("div.container.jumbotron")
      .should("have.length.at.least", 1)
    cy.get("button.btn.btn-primary").eq(0)
      .should("contain", "Add a bill")
      .click()
    cy.get("#type")
      .type("utilities")
      .should("have.value", "utilities")
    cy.get("#amount")
      .type("450")
      .should("have.value", "450")
    cy.get("#dueDate")
      .type("2018-02-15")
      .should("have.value", "2018-02-15")
    cy.get("input.btn.btn-success")
      .click()
    cy.get("div.container.jumbotron")
      .should("have.length.at.least", 1)
    cy.get("button.btn.btn-danger").eq(2)
      .click()
    cy.get("div.container.jumbotron")
      .should("have.length.at.least", 1)
    cy.reload()
    cy.get("button.btn.btn-primary").eq(1)
      .click()
    cy.get("canvas")
      .should("be.visible")
  })
})
